// Auto-generated by FORGE - DO NOT EDIT

#![allow(dead_code, unused_imports)]

use forge_dioxus::{
    ForgeClient, ForgeClientError, JobExecutionState, QueryState, SubscriptionState,
    WorkflowExecutionState,
};
use serde_json::json;

use super::types::*;
use super::{use_forge_job, use_forge_query, use_forge_subscription, use_forge_workflow};

pub fn use_track_account_verification(
    input: VerificationInput,
) -> dioxus::prelude::Signal<WorkflowExecutionState<VerificationOutput>> {
    use_forge_workflow("account_verification", input)
}
pub async fn create_user(
    client: &ForgeClient,
    email: String,
    name: String,
    role: Option<UserRole>,
) -> Result<User, ForgeClientError> {
    client
        .call(
            "create_user",
            json!({ "email": email, "name": name, "role": role }),
        )
        .await
}
pub async fn delete_user(client: &ForgeClient, id: String) -> Result<bool, ForgeClientError> {
    client.call("delete_user", json!({ "id": id })).await
}
pub fn use_track_export_users(
    input: ExportInput,
) -> dioxus::prelude::Signal<JobExecutionState<ExportOutput>> {
    use_forge_job("export_users", input)
}
pub async fn get_iss_location(
    client: &ForgeClient,
) -> Result<Option<IssLocation>, ForgeClientError> {
    client.call("get_iss_location", ()).await
}

pub fn use_get_iss_location() -> dioxus::prelude::Signal<QueryState<Option<IssLocation>>> {
    use_forge_query("get_iss_location", ())
}

pub fn use_get_iss_location_subscription()
-> dioxus::prelude::Signal<SubscriptionState<Option<IssLocation>>> {
    use_forge_subscription("get_iss_location", ())
}
pub async fn get_trades(client: &ForgeClient) -> Result<Vec<Trade>, ForgeClientError> {
    client.call("get_trades", ()).await
}

pub fn use_get_trades() -> dioxus::prelude::Signal<QueryState<Vec<Trade>>> {
    use_forge_query("get_trades", ())
}

pub fn use_get_trades_subscription() -> dioxus::prelude::Signal<SubscriptionState<Vec<Trade>>> {
    use_forge_subscription("get_trades", ())
}
pub async fn get_user(client: &ForgeClient, id: String) -> Result<Option<User>, ForgeClientError> {
    client.call("get_user", json!({ "id": id })).await
}

pub fn use_get_user(id: String) -> dioxus::prelude::Signal<QueryState<Option<User>>> {
    use_forge_query("get_user", json!({ "id": id }))
}

pub fn use_get_user_subscription(
    id: String,
) -> dioxus::prelude::Signal<SubscriptionState<Option<User>>> {
    use_forge_subscription("get_user", json!({ "id": id }))
}
pub async fn get_users(client: &ForgeClient) -> Result<Vec<User>, ForgeClientError> {
    client.call("get_users", ()).await
}

pub fn use_get_users() -> dioxus::prelude::Signal<QueryState<Vec<User>>> {
    use_forge_query("get_users", ())
}

pub fn use_get_users_subscription() -> dioxus::prelude::Signal<SubscriptionState<Vec<User>>> {
    use_forge_subscription("get_users", ())
}
pub async fn get_webhook_events(
    client: &ForgeClient,
) -> Result<Vec<WebhookEvent>, ForgeClientError> {
    client.call("get_webhook_events", ()).await
}

pub fn use_get_webhook_events() -> dioxus::prelude::Signal<QueryState<Vec<WebhookEvent>>> {
    use_forge_query("get_webhook_events", ())
}

pub fn use_get_webhook_events_subscription()
-> dioxus::prelude::Signal<SubscriptionState<Vec<WebhookEvent>>> {
    use_forge_subscription("get_webhook_events", ())
}

pub async fn update_user(
    client: &ForgeClient,
    id: String,
    email: Option<String>,
    name: Option<String>,
    role: Option<UserRole>,
) -> Result<User, ForgeClientError> {
    client
        .call(
            "update_user",
            json!({ "id": id, "email": email, "name": name, "role": role }),
        )
        .await
}
