// Auto-generated by FORGE - DO NOT EDIT

import { listSupportTicketsStore$ } from "./api";
import { toReactive, type ReactiveQuery } from "./runes.svelte";
import type { SupportTicket } from "./types";
export const listSupportTickets$ = (): ReactiveQuery<SupportTicket[]> =>
  toReactive(listSupportTicketsStore$());
