// Auto-generated by FORGE - DO NOT EDIT

export interface AddTicketNoteInput {
  id: string;
  note: string;
}

export interface CreateSupportTicketInput {
  customer_name: string;
  title: string;
  details: string;
  priority?: TicketPriority;
}

export interface McpAddTicketNoteInput {
  id: string;
  note: string;
}

export interface McpCreateSupportTicketInput {
  customer_name: string;
  title: string;
  details: string;
  priority: TicketPriority;
}

export interface McpSetTicketPriorityInput {
  id: string;
  priority: TicketPriority;
}

export interface McpSetTicketStatusInput {
  id: string;
  status: TicketStatus;
}

export interface McpTicket {
  id: string;
  customer_name: string;
  title: string;
  details: string;
  status: TicketStatus;
  priority: TicketPriority;
  last_note?: string;
  created_at: string;
  updated_at: string;
}

export interface SetTicketPriorityInput {
  id: string;
  priority: TicketPriority;
}

export interface SetTicketStatusInput {
  id: string;
  status: TicketStatus;
}

export interface SupportTicket {
  id: string;
  customer_name: string;
  title: string;
  details: string;
  status: TicketStatus;
  priority: TicketPriority;
  last_note?: string;
  created_at: string;
  updated_at: string;
}

export type TicketPriority = 'low' | 'normal' | 'high';

export type TicketStatus = 'new' | 'working' | 'resolved';

export type { ForgeError, QueryResult, SubscriptionResult } from "@forge/svelte";
