// Auto-generated by FORGE - DO NOT EDIT

import { getForgeClient, createSubscriptionStore, createJobStore, createWorkflowStore } from "@forge-rs/svelte";
import type {
  AuthResponse,
  CreateProjectInput,
  CreateTaskInput,
  DeleteTaskInput,
  ExportOutput,
  ExportProjectInput,
  GetProjectInput,
  ListProjectsInput,
  ListTasksInput,
  LoginInput,
  MoveTaskInput,
  Project,
  ProjectWithTasks,
  RegisterInput,
  ScheduleDeletionInput,
  ScheduleDeletionOutput,
  Task,
  UnarchiveProjectInput,
  UpdateProjectInput,
  UpdateTaskInput,
} from "./types";

// Queries
export const getProject = (args: GetProjectInput): Promise<ProjectWithTasks> =>
  getForgeClient().call("get_project", args);
export const listProjects = (args: ListProjectsInput): Promise<Project[]> =>
  getForgeClient().call("list_projects", args);
export const listTasks = (args: ListTasksInput): Promise<Task[]> =>
  getForgeClient().call("list_tasks", args);

// Subscriptions
export const getProjectStore$ = (args: GetProjectInput) =>
  createSubscriptionStore<GetProjectInput, ProjectWithTasks>("get_project", args);
export const listProjectsStore$ = (args: ListProjectsInput) =>
  createSubscriptionStore<ListProjectsInput, Project[]>("list_projects", args);
export const listTasksStore$ = (args: ListTasksInput) =>
  createSubscriptionStore<ListTasksInput, Task[]>("list_tasks", args);

// Mutations
export const createProject = (args: CreateProjectInput): Promise<Project> =>
  getForgeClient().call("create_project", args);
export const createTask = (args: CreateTaskInput): Promise<Task> =>
  getForgeClient().call("create_task", args);
export const deleteTask = (args: DeleteTaskInput): Promise<boolean> =>
  getForgeClient().call("delete_task", args);
export const login = (args: LoginInput): Promise<AuthResponse> =>
  getForgeClient().call("login", args);
export const moveTask = (args: MoveTaskInput): Promise<Task> =>
  getForgeClient().call("move_task", args);
export const register = (args: RegisterInput): Promise<AuthResponse> =>
  getForgeClient().call("register", args);
export const unarchiveProject = (args: UnarchiveProjectInput): Promise<Project> =>
  getForgeClient().call("unarchive_project", args);
export const updateProject = (args: UpdateProjectInput): Promise<Project> =>
  getForgeClient().call("update_project", args);
export const updateTask = (args: UpdateTaskInput): Promise<Task> =>
  getForgeClient().call("update_task", args);

// Jobs
export const trackExportProject = (args: ExportProjectInput) =>
  createJobStore<ExportProjectInput, ExportOutput>("export_project", args);

// Workflows
export const trackScheduleProjectArchive = (args: ScheduleDeletionInput) =>
  createWorkflowStore<ScheduleDeletionInput, ScheduleDeletionOutput>("schedule_project_archive", args);
