//! Dioxus API bindings generator.
//!
//! Generates `api.rs` with async functions and Dioxus hooks for
//! queries, mutations, jobs, and workflows. Uses `FunctionBinding`
//! and the shared `emit` module — no type mapping logic here.

use crate::Error;
use crate::binding::{BindingSet, FunctionBinding};
use crate::emit::{self};

pub fn generate(bindings: &BindingSet) -> Result<String, Error> {
    let mut output = String::from(
        "// Auto-generated by FORGE - DO NOT EDIT\n\n#![allow(dead_code, unused_imports)]\n\n",
    );
    output.push_str("use forge_dioxus::{\n");
    output.push_str("    ForgeClient, ForgeClientError, JobExecutionState, QueryState,\n");
    output.push_str("    SubscriptionState, WorkflowExecutionState,\n");
    output.push_str("};\n");
    output.push_str("use serde_json::json;\n\n");
    output.push_str("use super::types::*;\n");
    output.push_str(
        "use super::{use_forge_job, use_forge_query, use_forge_subscription, use_forge_workflow};\n\n",
    );

    for b in bindings.all() {
        let rendered = render_binding(b);
        if !rendered.is_empty() {
            output.push_str(&rendered);
            output.push('\n');
        }
    }

    Ok(output)
}

fn render_binding(b: &FunctionBinding) -> String {
    let fn_name = &b.name;
    let return_type = emit::dioxus_type(&b.return_type);
    let params = dioxus_params(b, true);
    let hook_params = dioxus_params(b, false);
    let call_args = dioxus_call_args(b);

    match b.kind {
        forge_core::schema::FunctionKind::Query => {
            format!(
                "pub async fn {fn_name}(client: &ForgeClient{params}) -> Result<{return_type}, ForgeClientError> {{\n    client.call(\"{fn_name}\", {call_args}).await\n}}\n\npub fn use_{fn_name}({hook_params}) -> dioxus::prelude::Signal<QueryState<{return_type}>> {{\n    use_forge_query(\"{fn_name}\", {call_args})\n}}\n\npub fn use_{fn_name}_subscription({hook_params}) -> dioxus::prelude::Signal<SubscriptionState<{return_type}>> {{\n    use_forge_subscription(\"{fn_name}\", {call_args})\n}}"
            )
        }
        forge_core::schema::FunctionKind::Mutation => {
            format!(
                "pub async fn {fn_name}(client: &ForgeClient{params}) -> Result<{return_type}, ForgeClientError> {{\n    client.call(\"{fn_name}\", {call_args}).await\n}}"
            )
        }
        forge_core::schema::FunctionKind::Job => {
            format!(
                "pub fn use_track_{fn_name}({hook_params}) -> dioxus::prelude::Signal<JobExecutionState<{return_type}>> {{\n    use_forge_job(\"{fn_name}\", {call_args})\n}}"
            )
        }
        forge_core::schema::FunctionKind::Workflow => {
            format!(
                "pub fn use_track_{fn_name}({hook_params}) -> dioxus::prelude::Signal<WorkflowExecutionState<{return_type}>> {{\n    use_forge_workflow(\"{fn_name}\", {call_args})\n}}"
            )
        }
        forge_core::schema::FunctionKind::Cron => String::new(),
    }
}

/// Build function parameter list for Dioxus.
/// When `with_client` is true, includes `client: &ForgeClient` prefix with leading comma.
fn dioxus_params(b: &FunctionBinding, with_client: bool) -> String {
    if b.args.is_empty() {
        return String::new();
    }

    let params: Vec<String> = b
        .args
        .iter()
        .map(|arg| format!("{}: {}", arg.name, emit::dioxus_type(&arg.rust_type)))
        .collect();

    if with_client {
        // Leading comma because client param comes first.
        format!(", {}", params.join(", "))
    } else {
        params.join(", ")
    }
}

/// Build the args expression for `client.call()` or hook invocations.
fn dioxus_call_args(b: &FunctionBinding) -> String {
    if b.args.is_empty() {
        return "()".into();
    }

    // Custom Args/Input struct: pass directly.
    if b.is_custom_args {
        return b
            .args
            .first()
            .map(|arg| arg.name.clone())
            .unwrap_or_else(|| "()".into());
    }

    // Single arg: json!({ "name": name })
    // Multiple args: json!({ "a": a, "b": b })
    let body: Vec<String> = b
        .args
        .iter()
        .map(|arg| format!("\"{}\": {}", arg.name, arg.name))
        .collect();
    format!("json!({{ {} }})", body.join(", "))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::binding::BindingSet;
    use forge_core::schema::{
        FunctionArg, FunctionDef, FunctionKind, RustType, SchemaRegistry, TableDef,
    };

    #[test]
    fn generates_query_with_args() {
        let registry = SchemaRegistry::new();
        let mut func = FunctionDef::query("get_user", RustType::Custom("User".into()));
        func.args.push(FunctionArg::new("id", RustType::Uuid));
        registry.register_function(func);

        let bindings = BindingSet::from_registry(&registry);
        let content = generate(&bindings).expect("query bindings should generate");

        assert!(content.contains("pub async fn get_user(client: &ForgeClient, id: String)"));
        assert!(content.contains("pub fn use_get_user(id: String)"));
        assert!(content.contains("pub fn use_get_user_subscription(id: String)"));
        assert!(content.contains("QueryState<User>"));
        assert!(content.contains("SubscriptionState<User>"));
    }

    #[test]
    fn generates_mutation() {
        let registry = SchemaRegistry::new();
        let mut func = FunctionDef::mutation("create_user", RustType::Custom("User".into()));
        func.args.push(FunctionArg::new("name", RustType::String));
        func.args.push(FunctionArg::new("email", RustType::String));
        registry.register_function(func);

        let bindings = BindingSet::from_registry(&registry);
        let content = generate(&bindings).expect("mutation bindings should generate");

        assert!(content.contains(
            "pub async fn create_user(client: &ForgeClient, name: String, email: String)"
        ));
        assert!(content.contains("json!({ \"name\": name, \"email\": email })"));
    }

    #[test]
    fn generates_no_arg_query() {
        let registry = SchemaRegistry::new();
        let func = FunctionDef::query(
            "list_users",
            RustType::Vec(Box::new(RustType::Custom("User".into()))),
        );
        registry.register_function(func);

        let bindings = BindingSet::from_registry(&registry);
        let content = generate(&bindings).expect("no-arg query should generate");

        assert!(content.contains("pub async fn list_users(client: &ForgeClient)"));
        assert!(content.contains("client.call(\"list_users\", ()).await"));
        assert!(content.contains("use_forge_query(\"list_users\", ())"));
    }

    #[test]
    fn generates_job_hook() {
        let registry = SchemaRegistry::new();
        let mut func = FunctionDef::new(
            "send_email",
            FunctionKind::Job,
            RustType::Custom("()".into()),
        );
        func.args.push(FunctionArg::new("to", RustType::String));
        registry.register_function(func);

        let bindings = BindingSet::from_registry(&registry);
        let content = generate(&bindings).expect("job bindings should generate");

        assert!(content.contains("pub fn use_track_send_email(to: String)"));
        assert!(content.contains("JobExecutionState"));
    }

    #[test]
    fn generates_workflow_hook() {
        let registry = SchemaRegistry::new();
        let func = FunctionDef::new(
            "onboard_user",
            FunctionKind::Workflow,
            RustType::Custom("User".into()),
        );
        registry.register_function(func);

        let bindings = BindingSet::from_registry(&registry);
        let content = generate(&bindings).expect("workflow bindings should generate");

        assert!(content.contains("use_track_onboard_user"));
        assert!(content.contains("WorkflowExecutionState<User>"));
    }

    #[test]
    fn custom_args_struct_passed_directly() {
        let registry = SchemaRegistry::new();

        // Register the DTO.
        let mut dto = TableDef::new("CreateUserArgs", "CreateUserArgs");
        dto.is_dto = true;
        registry.register_table(dto);

        let mut func = FunctionDef::mutation("create_user", RustType::Custom("User".into()));
        func.args.push(FunctionArg::new(
            "args",
            RustType::Custom("CreateUserArgs".into()),
        ));
        registry.register_function(func);

        let bindings = BindingSet::from_registry(&registry);
        let content = generate(&bindings).expect("custom args bindings should generate");

        // Should pass `args` directly, not wrapped in json!()
        assert!(content.contains("client.call(\"create_user\", args).await"));
    }

    #[test]
    fn skips_cron_functions() {
        let registry = SchemaRegistry::new();
        registry.register_function(FunctionDef::new(
            "daily_cleanup",
            FunctionKind::Cron,
            RustType::Custom("()".into()),
        ));

        let bindings = BindingSet::from_registry(&registry);
        let content = generate(&bindings).expect("cron filtering should generate");

        assert!(!content.contains("daily_cleanup"));
    }
}
