use forge_core::schema::{FunctionDef, FunctionKind, RustType, SchemaRegistry, TableDef};

use crate::Error;

#[derive(Default)]
pub struct ApiGenerator;

impl ApiGenerator {
    pub fn new() -> Self {
        Self
    }

    pub fn generate(&self, registry: &SchemaRegistry) -> Result<String, Error> {
        let mut output = String::from(
            "// Auto-generated by FORGE - DO NOT EDIT\n\n#![allow(dead_code, unused_imports)]\n\n",
        );
        output.push_str("use forge_dioxus::{\n");
        output.push_str("    ForgeClient, ForgeClientError, JobExecutionState, QueryState,\n");
        output.push_str("    SubscriptionState, WorkflowExecutionState,\n");
        output.push_str("};\n");
        output.push_str("use serde_json::json;\n\n");
        output.push_str("use super::types::*;\n");
        output.push_str("use super::{use_forge_job, use_forge_query, use_forge_subscription, use_forge_workflow};\n\n");

        let dto_tables: Vec<TableDef> = registry.all_tables();
        for function in registry.all_functions() {
            output.push_str(&render_function(&function, &dto_tables));
            output.push('\n');
        }

        Ok(output)
    }
}

fn render_function(function: &FunctionDef, tables: &[TableDef]) -> String {
    let fn_name = function.name.as_str();
    let return_type = rust_type_to_rust(&function.return_type);
    let wrapped_args = wrapped_args_expression(function, tables);
    let params = function_params(function, tables);

    match function.kind {
        FunctionKind::Query => {
            let hook_params = hook_params(function, tables);
            let hook_args = hook_args_expression(function, tables);
            format!(
                "pub async fn {fn_name}(client: &ForgeClient{params}) -> Result<{return_type}, ForgeClientError> {{\n    client.call(\"{fn_name}\", {wrapped_args}).await\n}}\n\npub fn use_{fn_name}({hook_params}) -> dioxus::prelude::Signal<QueryState<{return_type}>> {{\n    use_forge_query(\"{fn_name}\", {hook_args})\n}}\n\npub fn use_{fn_name}_subscription({hook_params}) -> dioxus::prelude::Signal<SubscriptionState<{return_type}>> {{\n    use_forge_subscription(\"{fn_name}\", {hook_args})\n}}"
            )
        }
        FunctionKind::Mutation => format!(
            "pub async fn {fn_name}(client: &ForgeClient{params}) -> Result<{return_type}, ForgeClientError> {{\n    client.call(\"{fn_name}\", {wrapped_args}).await\n}}"
        ),
        FunctionKind::Job => {
            let hook_params = hook_params(function, tables);
            let hook_args = hook_args_expression(function, tables);
            format!(
                "pub fn use_track_{fn_name}({hook_params}) -> dioxus::prelude::Signal<JobExecutionState<{return_type}>> {{\n    use_forge_job(\"{fn_name}\", {hook_args})\n}}"
            )
        }
        FunctionKind::Workflow => {
            let hook_params = hook_params(function, tables);
            let hook_args = hook_args_expression(function, tables);
            format!(
                "pub fn use_track_{fn_name}({hook_params}) -> dioxus::prelude::Signal<WorkflowExecutionState<{return_type}>> {{\n    use_forge_workflow(\"{fn_name}\", {hook_args})\n}}"
            )
        }
        FunctionKind::Cron => String::new(),
    }
}

fn function_params(function: &FunctionDef, tables: &[TableDef]) -> String {
    match function.args.as_slice() {
        [] => String::new(),
        [arg] if is_custom_args_type(&arg.rust_type, tables) => {
            format!(", {}: {}", arg.name, rust_type_to_rust(&arg.rust_type))
        }
        args => args
            .iter()
            .map(|arg| format!(", {}: {}", arg.name, rust_type_to_rust(&arg.rust_type)))
            .collect::<String>(),
    }
}

fn hook_params(function: &FunctionDef, tables: &[TableDef]) -> String {
    match function.args.as_slice() {
        [] => String::new(),
        [arg] if is_custom_args_type(&arg.rust_type, tables) => {
            format!("{}: {}", arg.name, rust_type_to_rust(&arg.rust_type))
        }
        args => args
            .iter()
            .map(|arg| format!("{}: {}", arg.name, rust_type_to_rust(&arg.rust_type)))
            .collect::<Vec<_>>()
            .join(", "),
    }
}

fn wrapped_args_expression(function: &FunctionDef, tables: &[TableDef]) -> String {
    match function.args.as_slice() {
        [] => "()".to_string(),
        [arg] if is_custom_args_type(&arg.rust_type, tables) => arg.name.clone(),
        [arg] => format!("json!({{ \"{}\": {} }})", arg.name, arg.name),
        args => {
            let body = args
                .iter()
                .map(|arg| format!("\"{}\": {}", arg.name, arg.name))
                .collect::<Vec<_>>()
                .join(", ");
            format!("json!({{ {body} }})")
        }
    }
}

fn hook_args_expression(function: &FunctionDef, tables: &[TableDef]) -> String {
    wrapped_args_expression(function, tables)
}

fn is_custom_args_type(rust_type: &RustType, tables: &[TableDef]) -> bool {
    match rust_type {
        RustType::Custom(name) => {
            (name.ends_with("Args") || name.contains("Args") || name.ends_with("Input"))
                && tables.iter().any(|table| table.struct_name == *name)
        }
        _ => false,
    }
}

fn rust_type_to_rust(rust_type: &RustType) -> String {
    match rust_type {
        RustType::String | RustType::Uuid => "String".to_string(),
        RustType::I32 => "i32".to_string(),
        RustType::I64 => "i64".to_string(),
        RustType::F32 => "f32".to_string(),
        RustType::F64 => "f64".to_string(),
        RustType::Bool => "bool".to_string(),
        RustType::DateTime
        | RustType::Date
        | RustType::Instant
        | RustType::LocalDate
        | RustType::LocalTime => "String".to_string(),
        RustType::Upload => "forge_dioxus::ForgeUpload".to_string(),
        RustType::Json => "serde_json::Value".to_string(),
        RustType::Bytes => "Vec<u8>".to_string(),
        RustType::Option(inner) => format!("Option<{}>", rust_type_to_rust(inner)),
        RustType::Vec(inner) => format!("Vec<{}>", rust_type_to_rust(inner)),
        RustType::Custom(name) => match name.as_str() {
            "Uuid" | "uuid::Uuid" => "String".to_string(),
            "DateTime<Utc>" | "NaiveDate" | "NaiveDateTime" | "Instant" | "LocalDate"
            | "LocalTime" | "Timestamp" => "String".to_string(),
            "Value" | "serde_json::Value" => "serde_json::Value".to_string(),
            "Bytes" => "Vec<u8>".to_string(),
            "Upload" => "forge_dioxus::ForgeUpload".to_string(),
            other => other.to_string(),
        },
    }
}
