mod api;
mod types;

pub use api::ApiGenerator;
pub use types::TypeGenerator;

use std::path::PathBuf;

use forge_core::schema::SchemaRegistry;

use crate::Error;

pub struct DioxusGenerator {
    output_dir: PathBuf,
    type_gen: TypeGenerator,
    api_gen: ApiGenerator,
}

impl DioxusGenerator {
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        let output_dir = output_dir.into();
        Self {
            output_dir: output_dir.clone(),
            type_gen: TypeGenerator::new(),
            api_gen: ApiGenerator::new(),
        }
    }

    pub fn generate(&self, registry: &SchemaRegistry) -> Result<(), Error> {
        std::fs::create_dir_all(&self.output_dir)?;
        std::fs::write(
            self.output_dir.join("types.rs"),
            self.type_gen.generate(registry)?,
        )?;
        std::fs::write(
            self.output_dir.join("api.rs"),
            self.api_gen.generate(registry)?,
        )?;
        std::fs::write(self.output_dir.join("mod.rs"), self.generate_mod())?;
        Ok(())
    }

    fn generate_mod(&self) -> String {
        r#"// Auto-generated by FORGE - DO NOT EDIT

#![allow(dead_code, unused_imports)]

pub mod api;
pub mod types;

pub use api::*;
pub use forge_dioxus::{
    ConnectionState, ForgeClient, ForgeClientConfig, ForgeClientError, ForgeError,
    ForgeProvider, ForgeUpload, JobExecutionState, QueryState, SubscriptionHandle,
    SubscriptionState, WorkflowExecutionState, use_connection_state, use_forge_client,
    use_forge_job, use_forge_query, use_forge_subscription, use_forge_workflow,
};
pub use types::*;
"#
        .to_string()
    }
}
