use forge_core::schema::{RustType, SchemaRegistry, TableDef};

use crate::Error;

#[derive(Default)]
pub struct TypeGenerator;

impl TypeGenerator {
    pub fn new() -> Self {
        Self
    }

    pub fn generate(&self, registry: &SchemaRegistry) -> Result<String, Error> {
        let mut output =
            String::from("// Auto-generated by FORGE - DO NOT EDIT\n\n#![allow(dead_code)]\n\n");
        output.push_str("use serde::{Deserialize, Serialize};\n");

        let uses_upload = registry.all_tables().iter().any(|table| {
            table
                .fields
                .iter()
                .any(|field| contains_upload(&field.rust_type))
        });
        let uses_json = registry.all_tables().iter().any(|table| {
            table
                .fields
                .iter()
                .any(|field| contains_json(&field.rust_type))
        });

        if uses_upload {
            output.push_str("use forge_dioxus::ForgeUpload;\n");
        }
        if uses_json {
            output.push_str("use serde_json::Value as JsonValue;\n");
        }
        if uses_upload || uses_json {
            output.push('\n');
        }

        let mut tables = registry.all_tables();
        tables.sort_by(|a, b| a.struct_name.cmp(&b.struct_name));
        for table in tables {
            output.push_str(&render_table(&table));
            output.push('\n');
        }

        let mut enums = registry.all_enums();
        enums.sort_by(|a, b| a.name.cmp(&b.name));
        for enum_def in enums {
            output.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
            output.push_str("#[serde(rename_all = \"snake_case\")]\n");
            output.push_str(&format!("pub enum {} {{\n", enum_def.name));
            for variant in enum_def.variants {
                output.push_str(&format!("    {},\n", variant.name));
            }
            output.push_str("}\n\n");
        }

        Ok(output)
    }
}

fn render_table(table: &TableDef) -> String {
    let has_upload = table
        .fields
        .iter()
        .any(|field| contains_upload(&field.rust_type));
    let derives = if has_upload {
        "#[derive(Debug, Clone)]\n"
    } else {
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n"
    };

    let mut output = String::new();
    output.push_str(derives);
    output.push_str(&format!("pub struct {} {{\n", table.struct_name));
    for field in &table.fields {
        output.push_str(&format!(
            "    pub {}: {},\n",
            field.name,
            rust_type_to_rust(&field.rust_type)
        ));
    }
    output.push_str("}\n");
    output
}

fn rust_type_to_rust(rust_type: &RustType) -> String {
    match rust_type {
        RustType::String | RustType::Uuid => "String".to_string(),
        RustType::I32 => "i32".to_string(),
        RustType::I64 => "i64".to_string(),
        RustType::F32 => "f32".to_string(),
        RustType::F64 => "f64".to_string(),
        RustType::Bool => "bool".to_string(),
        RustType::DateTime
        | RustType::Date
        | RustType::Instant
        | RustType::LocalDate
        | RustType::LocalTime => "String".to_string(),
        RustType::Upload => "ForgeUpload".to_string(),
        RustType::Json => "JsonValue".to_string(),
        RustType::Bytes => "Vec<u8>".to_string(),
        RustType::Option(inner) => format!("Option<{}>", rust_type_to_rust(inner)),
        RustType::Vec(inner) => format!("Vec<{}>", rust_type_to_rust(inner)),
        RustType::Custom(name) => match name.as_str() {
            "Uuid" | "uuid::Uuid" => "String".to_string(),
            "DateTime<Utc>" | "NaiveDate" | "NaiveDateTime" | "Instant" | "LocalDate"
            | "LocalTime" | "Timestamp" => "String".to_string(),
            "Value" | "serde_json::Value" => "JsonValue".to_string(),
            "Bytes" => "Vec<u8>".to_string(),
            "Upload" => "ForgeUpload".to_string(),
            other => other.to_string(),
        },
    }
}

fn contains_upload(rust_type: &RustType) -> bool {
    match rust_type {
        RustType::Upload => true,
        RustType::Option(inner) | RustType::Vec(inner) => contains_upload(inner),
        RustType::Custom(name) => name == "Upload",
        _ => false,
    }
}

fn contains_json(rust_type: &RustType) -> bool {
    match rust_type {
        RustType::Json => true,
        RustType::Option(inner) | RustType::Vec(inner) => contains_json(inner),
        RustType::Custom(name) => name == "Value" || name == "serde_json::Value",
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::rust_type_to_rust;
    use forge_core::schema::RustType;

    #[test]
    fn maps_timestamp_alias_to_string() {
        assert_eq!(
            rust_type_to_rust(&RustType::Custom("Timestamp".to_string())),
            "String"
        );
    }
}
