// Auto-generated by FORGE - DO NOT EDIT

import { getDemoStatsStore$, getIssLocationStore$, getTradesStore$, getUserStore$, getUsersStore$, getWebhookEventsStore$ } from "./api";
import { toReactive, type ReactiveQuery } from "./runes.svelte";
import type { DemoStats, IssLocation, Trade, User, WebhookEvent } from "./types";
export const getDemoStats$ = (): ReactiveQuery<DemoStats> =>
  toReactive(getDemoStatsStore$());
export const getIssLocation$ = (): ReactiveQuery<IssLocation | null> =>
  toReactive(getIssLocationStore$());
export const getTrades$ = (): ReactiveQuery<Trade[]> =>
  toReactive(getTradesStore$());
export const getUser$ = (args: { id: string }): ReactiveQuery<User | null> =>
  toReactive(getUserStore$(args));
export const getUsers$ = (): ReactiveQuery<User[]> =>
  toReactive(getUsersStore$());
export const getWebhookEvents$ = (): ReactiveQuery<WebhookEvent[]> =>
  toReactive(getWebhookEventsStore$());
