apiVersion: 1
datasources:
  - name: Forge PostgreSQL
    type: grafana-postgresql-datasource
    uid: forge_pg
    url: $POSTGRES_HOST:$POSTGRES_PORT
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    editable: true
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1800
      timescaledb: false
