//! Automatic function registration via the `inventory` crate.
//!
//! Each `#[forge::query]`, `#[forge::mutation]`, etc. macro emits an
//! `inventory::submit!` call that registers a factory function. Calling
//! `ForgeBuilder::auto_register()` collects all submitted entries and
//! registers them with the appropriate registry.
//!
//! Auto-registration entries are gated by the same feature flags as the
//! runtime registries they target. Code generated by `#[forge::job]` always
//! references `forge::AutoJob` — if the user's app doesn't enable the `jobs`
//! feature, they get a clean compile error at the macro call site.

use forge_runtime::function::FunctionRegistry;

#[cfg(feature = "cron")]
use forge_runtime::cron::CronRegistry;
#[cfg(feature = "daemons")]
use forge_runtime::daemon::DaemonRegistry;
#[cfg(feature = "jobs")]
use forge_runtime::jobs::JobRegistry;
#[cfg(feature = "gateway")]
use forge_runtime::mcp::McpToolRegistry;
#[cfg(feature = "gateway")]
use forge_runtime::webhook::WebhookRegistry;
#[cfg(feature = "workflows")]
use forge_runtime::workflow::WorkflowRegistry;

pub struct AutoQuery(pub fn(&mut FunctionRegistry));
pub struct AutoMutation(pub fn(&mut FunctionRegistry));

#[cfg(feature = "jobs")]
pub struct AutoJob(pub fn(&mut JobRegistry));
#[cfg(feature = "cron")]
pub struct AutoCron(pub fn(&mut CronRegistry));
#[cfg(feature = "workflows")]
pub struct AutoWorkflow(pub fn(&mut WorkflowRegistry));
#[cfg(feature = "daemons")]
pub struct AutoDaemon(pub fn(&mut DaemonRegistry));
#[cfg(feature = "gateway")]
pub struct AutoWebhook(pub fn(&mut WebhookRegistry));
#[cfg(feature = "gateway")]
pub struct AutoMcpTool(pub fn(&mut McpToolRegistry));

inventory::collect!(AutoQuery);
inventory::collect!(AutoMutation);
#[cfg(feature = "jobs")]
inventory::collect!(AutoJob);
#[cfg(feature = "cron")]
inventory::collect!(AutoCron);
#[cfg(feature = "workflows")]
inventory::collect!(AutoWorkflow);
#[cfg(feature = "daemons")]
inventory::collect!(AutoDaemon);
#[cfg(feature = "gateway")]
inventory::collect!(AutoWebhook);
#[cfg(feature = "gateway")]
inventory::collect!(AutoMcpTool);

/// Register all auto-discovered functions into the builder's registries.
#[allow(clippy::too_many_arguments)]
pub fn auto_register_all(
    functions: &mut FunctionRegistry,
    #[cfg(feature = "jobs")] jobs: &mut JobRegistry,
    #[cfg(feature = "cron")] crons: &mut CronRegistry,
    #[cfg(feature = "workflows")] workflows: &mut WorkflowRegistry,
    #[cfg(feature = "daemons")] daemons: &mut DaemonRegistry,
    #[cfg(feature = "gateway")] webhooks: &mut WebhookRegistry,
    #[cfg(feature = "gateway")] mcp_tools: &mut McpToolRegistry,
) {
    for entry in inventory::iter::<AutoQuery> {
        (entry.0)(functions);
    }
    for entry in inventory::iter::<AutoMutation> {
        (entry.0)(functions);
    }
    #[cfg(feature = "jobs")]
    for entry in inventory::iter::<AutoJob> {
        (entry.0)(jobs);
    }
    #[cfg(feature = "cron")]
    for entry in inventory::iter::<AutoCron> {
        (entry.0)(crons);
    }
    #[cfg(feature = "workflows")]
    for entry in inventory::iter::<AutoWorkflow> {
        (entry.0)(workflows);
    }
    #[cfg(feature = "daemons")]
    for entry in inventory::iter::<AutoDaemon> {
        (entry.0)(daemons);
    }
    #[cfg(feature = "gateway")]
    for entry in inventory::iter::<AutoWebhook> {
        (entry.0)(webhooks);
    }
    #[cfg(feature = "gateway")]
    for entry in inventory::iter::<AutoMcpTool> {
        (entry.0)(mcp_tools);
    }
}
