//! Runtime Generator
//!
//! Generates the local frontend runtime package under `.forge/<target>/`.
//! The runtime is regenerated by `forge generate` to keep it in sync with the CLI version.

use anyhow::Result;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use super::frontend_target::FrontendTarget;
use super::template::render;
use crate::template_vars;

/// Current FORGE CLI version (used for version tracking)
pub const FORGE_VERSION: &str = env!("CARGO_PKG_VERSION");

fn dioxus_internal_module(content: &str) -> String {
    let marker = "\n\nuse ";
    if let Some(index) = content.find(marker) {
        let (head, tail) = content.split_at(index);
        format!("{head}\n\n#![allow(dead_code)]{tail}")
    } else {
        let marker = "\n\n#[derive";
        if let Some(index) = content.find(marker) {
            let (head, tail) = content.split_at(index);
            format!("{head}\n\n#![allow(dead_code)]{tail}")
        } else {
            format!("#![allow(dead_code)]\n\n{content}")
        }
    }
}

/// Check if the project has a legacy runtime structure (embedded in src/lib/forge/runtime/)
pub fn has_legacy_runtime(frontend_dir: &Path) -> bool {
    frontend_dir.join("src/lib/forge/runtime/index.ts").exists()
}

/// Get the version of the runtime currently installed in the project
pub fn get_installed_version(frontend_dir: &Path) -> Option<String> {
    let version_file = frontend_dir.join(".forge/version");
    fs::read_to_string(version_file)
        .ok()
        .map(|s| s.trim().to_string())
}

/// Check if a runtime update is needed
pub fn needs_update(frontend_dir: &Path, target: FrontendTarget) -> bool {
    let checksums_missing = !frontend_dir.join(".forge/checksums.json").exists();
    let runtime_missing = !frontend_dir
        .join(".forge")
        .join(target.runtime_dir_name())
        .exists();
    match get_installed_version(frontend_dir) {
        Some(installed) => installed != FORGE_VERSION || checksums_missing || runtime_missing,
        None => true,
    }
}

/// Compute SHA-256 hex digest of content.
fn sha256_hex(content: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content);
    format!("{:x}", hasher.finalize())
}

pub fn generate_runtime(frontend_dir: &Path, target: FrontendTarget) -> Result<()> {
    let forge_dir = frontend_dir.join(".forge");
    fs::create_dir_all(forge_dir.join(target.runtime_dir_name()))?;

    fs::write(forge_dir.join("version"), FORGE_VERSION)?;

    let vars = template_vars!("version" => FORGE_VERSION);
    let files = target
        .runtime_templates()
        .iter()
        .map(|file| {
            let rendered = render(file.template, &vars);
            let content = if file.allow_dead_code {
                dioxus_internal_module(&rendered)
            } else {
                rendered
            };
            (file.path, content)
        })
        .collect::<Vec<_>>();

    let mut checksums = BTreeMap::new();
    for (rel_path, content) in &files {
        if let Some(parent) = forge_dir.join(rel_path).parent() {
            fs::create_dir_all(parent)?;
        }
        checksums.insert(rel_path.to_string(), sha256_hex(content.as_bytes()));
        fs::write(forge_dir.join(rel_path), content)?;
    }

    // Write checksums file
    let checksums_json = serde_json::to_string_pretty(&checksums)?;
    fs::write(forge_dir.join("checksums.json"), checksums_json)?;

    Ok(())
}

/// Verify generated files against stored checksums.
/// Returns a list of files that have been modified or are missing.
pub fn verify_checksums(frontend_dir: &Path) -> Result<Vec<ChecksumMismatch>> {
    let forge_dir = frontend_dir.join(".forge");
    let checksums_path = forge_dir.join("checksums.json");

    if !checksums_path.exists() {
        return Ok(vec![ChecksumMismatch {
            file: "checksums.json".to_string(),
            kind: MismatchKind::Missing,
        }]);
    }

    let content = fs::read_to_string(&checksums_path)?;
    let checksums: BTreeMap<String, String> = serde_json::from_str(&content)?;

    let mut mismatches = Vec::new();
    for (rel_path, expected_hash) in &checksums {
        let file_path = forge_dir.join(rel_path);
        if !file_path.exists() {
            mismatches.push(ChecksumMismatch {
                file: rel_path.clone(),
                kind: MismatchKind::Missing,
            });
        } else {
            let actual = fs::read(&file_path)?;
            let actual_hash = sha256_hex(&actual);
            if actual_hash != *expected_hash {
                mismatches.push(ChecksumMismatch {
                    file: rel_path.clone(),
                    kind: MismatchKind::Modified,
                });
            }
        }
    }

    Ok(mismatches)
}

pub struct ChecksumMismatch {
    pub file: String,
    pub kind: MismatchKind,
}

pub enum MismatchKind {
    Modified,
    Missing,
}

/// Remove legacy runtime directory (src/lib/forge/runtime/)
pub fn remove_legacy_runtime(frontend_dir: &Path) -> Result<()> {
    let legacy_dir = frontend_dir.join("src/lib/forge/runtime");
    if legacy_dir.exists() {
        fs::remove_dir_all(legacy_dir)?;
    }
    Ok(())
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::indexing_slicing)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_generate_runtime() {
        let dir = tempdir().unwrap();
        generate_runtime(dir.path(), FrontendTarget::SvelteKit).unwrap();

        assert!(dir.path().join(".forge/version").exists());
        assert!(dir.path().join(".forge/svelte/package.json").exists());
        assert!(dir.path().join(".forge/svelte/index.ts").exists());
        assert!(dir.path().join(".forge/svelte/types.ts").exists());
        assert!(dir.path().join(".forge/svelte/client.ts").exists());
        assert!(dir.path().join(".forge/svelte/context.ts").exists());
        assert!(dir.path().join(".forge/svelte/stores.ts").exists());
        assert!(dir.path().join(".forge/svelte/datetime.ts").exists());
        assert!(
            dir.path()
                .join(".forge/svelte/ForgeProvider.svelte")
                .exists()
        );
    }

    #[test]
    fn test_version_file() {
        let dir = tempdir().unwrap();
        generate_runtime(dir.path(), FrontendTarget::SvelteKit).unwrap();

        let version = fs::read_to_string(dir.path().join(".forge/version")).unwrap();
        assert_eq!(version.trim(), FORGE_VERSION);
    }

    #[test]
    fn test_needs_update() {
        let dir = tempdir().unwrap();

        assert!(needs_update(dir.path(), FrontendTarget::SvelteKit));

        generate_runtime(dir.path(), FrontendTarget::SvelteKit).unwrap();

        assert!(!needs_update(dir.path(), FrontendTarget::SvelteKit));

        fs::write(dir.path().join(".forge/version"), "0.0.0").unwrap();
        assert!(needs_update(dir.path(), FrontendTarget::SvelteKit));
    }

    #[test]
    fn test_has_legacy_runtime() {
        let dir = tempdir().unwrap();

        // No legacy runtime
        assert!(!has_legacy_runtime(dir.path()));

        // Create legacy structure
        let legacy_dir = dir.path().join("src/lib/forge/runtime");
        fs::create_dir_all(&legacy_dir).unwrap();
        fs::write(legacy_dir.join("index.ts"), "// legacy").unwrap();

        assert!(has_legacy_runtime(dir.path()));
    }

    #[test]
    fn test_generate_dioxus_runtime() {
        let dir = tempdir().unwrap();
        generate_runtime(dir.path(), FrontendTarget::Dioxus).unwrap();

        assert!(dir.path().join(".forge/dioxus/Cargo.toml").exists());
        assert!(dir.path().join(".forge/dioxus/src/lib.rs").exists());
        assert!(dir.path().join(".forge/dioxus/src/client.rs").exists());
    }
}
