// Auto-generated by FORGE v0.6.0 - DO NOT EDIT
// Regenerate with: forge generate

use dioxus::prelude::*;

use crate::{ConnectionState, ForgeClient, ForgeClientConfig};

#[component]
pub fn ForgeProvider(url: String, children: Element) -> Element {
    let connection_state = use_context_provider(|| Signal::new(ConnectionState::Disconnected));
    use_context_provider(|| {
        let config = ForgeClientConfig::new(url).with_connection_state(connection_state);
        ForgeClient::new(config)
    });

    rsx! { {children} }
}

pub fn use_forge_client() -> ForgeClient {
    use_context::<ForgeClient>()
}

pub fn use_connection_state() -> Signal<ConnectionState> {
    use_context::<Signal<ConnectionState>>()
}
