// Auto-generated by FORGE v0.6.0 - DO NOT EDIT
// Regenerate with: forge generate

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct ForgeError {
    pub code: String,
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ForgeClientError {
    pub code: String,
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
}

impl ForgeClientError {
    pub fn new(
        code: impl Into<String>,
        message: impl Into<String>,
        details: Option<serde_json::Value>,
    ) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
            details,
        }
    }

    pub fn as_forge_error(&self) -> ForgeError {
        ForgeError {
            code: self.code.clone(),
            message: self.message.clone(),
            details: self.details.clone(),
        }
    }
}

impl std::fmt::Display for ForgeClientError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.code, self.message)
    }
}

impl std::error::Error for ForgeClientError {}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ConnectionState {
    #[default]
    Disconnected,
    Connecting,
    Connected,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct QueryState<T> {
    pub loading: bool,
    pub data: Option<T>,
    pub error: Option<ForgeError>,
}

impl<T> Default for QueryState<T> {
    fn default() -> Self {
        Self {
            loading: true,
            data: None,
            error: None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionState<T> {
    pub loading: bool,
    pub data: Option<T>,
    pub error: Option<ForgeError>,
    pub stale: bool,
    pub connection_state: ConnectionState,
}

impl<T> Default for SubscriptionState<T> {
    fn default() -> Self {
        Self {
            loading: true,
            data: None,
            error: None,
            stale: false,
            connection_state: ConnectionState::Disconnected,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobStatus {
    Pending,
    Claimed,
    Running,
    Completed,
    Retry,
    Failed,
    DeadLetter,
    CancelRequested,
    Cancelled,
    NotFound,
}

impl Default for JobStatus {
    fn default() -> Self {
        Self::Pending
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct JobState<TOutput> {
    pub job_id: String,
    pub status: JobStatus,
    pub progress: Option<f64>,
    pub message: Option<String>,
    pub output: Option<TOutput>,
    pub error: Option<String>,
}

impl<TOutput> Default for JobState<TOutput> {
    fn default() -> Self {
        Self {
            job_id: String::new(),
            status: JobStatus::Pending,
            progress: None,
            message: None,
            output: None,
            error: None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct JobExecutionState<TOutput> {
    pub loading: bool,
    pub connection_state: ConnectionState,
    pub state: JobState<TOutput>,
}

impl<TOutput> Default for JobExecutionState<TOutput> {
    fn default() -> Self {
        Self {
            loading: true,
            connection_state: ConnectionState::Disconnected,
            state: JobState::default(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WorkflowStatus {
    Created,
    Running,
    Waiting,
    Completed,
    Compensating,
    Compensated,
    Failed,
    NotFound,
}

impl Default for WorkflowStatus {
    fn default() -> Self {
        Self::Created
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct WorkflowStepState {
    pub name: String,
    pub status: String,
    pub error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WorkflowState<TOutput> {
    pub workflow_id: String,
    pub status: WorkflowStatus,
    pub step: Option<String>,
    pub waiting_for: Option<String>,
    pub steps: Vec<WorkflowStepState>,
    pub output: Option<TOutput>,
    pub error: Option<String>,
}

impl<TOutput> Default for WorkflowState<TOutput> {
    fn default() -> Self {
        Self {
            workflow_id: String::new(),
            status: WorkflowStatus::Created,
            step: None,
            waiting_for: None,
            steps: Vec::new(),
            output: None,
            error: None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WorkflowExecutionState<TOutput> {
    pub loading: bool,
    pub connection_state: ConnectionState,
    pub state: WorkflowState<TOutput>,
}

impl<TOutput> Default for WorkflowExecutionState<TOutput> {
    fn default() -> Self {
        Self {
            loading: true,
            connection_state: ConnectionState::Disconnected,
            state: WorkflowState::default(),
        }
    }
}

#[derive(Debug, Clone)]
pub enum StreamEvent<T> {
    Connection(ConnectionState),
    Data(T),
    Error(ForgeClientError),
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct RpcEnvelopeRaw {
    pub success: bool,
    #[serde(default)]
    pub data: Option<serde_json::Value>,
    #[serde(default)]
    pub error: Option<ForgeError>,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct ConnectedEvent {
    pub session_id: Option<String>,
    pub session_secret: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct SseEnvelopeRaw {
    pub target: Option<String>,
    #[serde(default)]
    pub payload: Option<serde_json::Value>,
    #[serde(default)]
    pub code: Option<String>,
    #[serde(default)]
    pub message: Option<String>,
    #[serde(default)]
    pub session_id: Option<String>,
    #[serde(default)]
    pub session_secret: Option<String>,
}
