// Auto-generated by FORGE - DO NOT EDIT

import { getProjectStore$, listProjectsStore$, listTasksStore$ } from "./api";
import { toReactive, type ReactiveQuery } from "./runes.svelte";
import type { GetProjectInput, ListProjectsInput, ListTasksInput, Project, ProjectWithTasks, Task } from "./types";
export const getProject$ = (args: GetProjectInput): ReactiveQuery<ProjectWithTasks> =>
  toReactive(getProjectStore$(args));
export const listProjects$ = (args: ListProjectsInput): ReactiveQuery<Project[]> =>
  toReactive(listProjectsStore$(args));
export const listTasks$ = (args: ListTasksInput): ReactiveQuery<Task[]> =>
  toReactive(listTasksStore$(args));
