// Auto-generated by FORGE - DO NOT EDIT

export interface AuthResponse {
  token: string;
  user: UserPublic;
}

export interface CreateProjectInput {
  user_id: string;
  name: string;
  description: string;
}

export interface CreateTaskInput {
  user_id: string;
  project_id: string;
  title: string;
  description: string;
  priority?: TaskPriority;
  assignee_id?: string;
}

export interface DeleteTaskInput {
  user_id: string;
  id: string;
}

export interface ExportOutput {
  data: string;
  task_count: number;
}

export interface ExportProjectInput {
  user_id: string;
  project_id: string;
  format: ExportFormat;
}

export interface GetProjectInput {
  id: string;
  user_id: string;
}

export interface ListProjectsInput {
  user_id: string;
}

export interface ListTasksInput {
  user_id: string;
  project_id: string;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface MoveTaskInput {
  user_id: string;
  id: string;
  status: TaskStatus;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  owner_id: string;
  archived: boolean;
  archive_started_at?: string;
  archive_delete_at?: string;
  created_at: string;
}

export interface ProjectWithTasks {
  project: Project;
  tasks: Task[];
}

export interface RegisterInput {
  email: string;
  name: string;
  password: string;
}

export interface ScheduleDeletionInput {
  user_id: string;
  project_id: string;
}

export interface ScheduleDeletionOutput {
  tasks_deleted: number;
}

export interface Task {
  id: string;
  project_id: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  assignee_id?: string;
  due_date?: string;
  position: number;
  created_at: string;
  updated_at: string;
}

export interface UnarchiveProjectInput {
  user_id: string;
  id: string;
}

export interface UpdateProjectInput {
  user_id: string;
  id: string;
  name?: string;
  description?: string;
}

export interface UpdateTaskInput {
  user_id: string;
  id: string;
  title?: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  assignee_id?: string;
  due_date?: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
  password_hash: string;
  created_at: string;
}

export interface UserPublic {
  id: string;
  email: string;
  name: string;
}

export type ExportFormat = 'csv' | 'json';

export type TaskPriority = 'low' | 'medium' | 'high';

export type TaskStatus = 'backlog' | 'todo' | 'in_progress' | 'done';

export type { ForgeError, QueryResult, SubscriptionResult } from "@forge/svelte";
