// Auto-generated by FORGE - DO NOT EDIT

import { listTodosStore$ } from "./api";
import { toReactive, type ReactiveQuery } from "./runes.svelte";
import type { Todo } from "./types";
export const listTodos$ = (): ReactiveQuery<Todo[]> =>
  toReactive(listTodosStore$());
