// Auto-generated by FORGE - DO NOT EDIT

export interface CreateTodoInput {
  title: string;
}

export interface Todo {
  id: string;
  title: string;
  completed: boolean;
  created_at: string;
}

export interface UpdateTodoInput {
  id: string;
  title?: string;
  completed?: boolean;
}

export type { ForgeError, QueryResult, SubscriptionResult } from "@forge/svelte";
