use std::path::PathBuf;

use forge_core::schema::{FunctionKind, RustType, SchemaRegistry};

use super::Error;

/// Generates TypeScript API bindings.
pub struct ApiGenerator {
    #[allow(dead_code)]
    output_dir: PathBuf,
}

impl ApiGenerator {
    /// Create a new API generator.
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        Self {
            output_dir: output_dir.into(),
        }
    }

    pub fn generate(&self, registry: &SchemaRegistry) -> Result<String, Error> {
        let mut output = String::new();
        let mut type_imports: Vec<String> = Vec::new();
        let functions = registry.all_functions();
        let mut bindings: Vec<String> = Vec::new();
        let mut queries: Vec<String> = Vec::new();
        let mut mutations: Vec<String> = Vec::new();
        let mut jobs: Vec<String> = Vec::new();
        let mut workflows: Vec<String> = Vec::new();

        for func in &functions {
            let args_type = if func.args.is_empty() {
                "Record<string, never>".to_string()
            } else if func.args.len() == 1 {
                let arg = &func.args[0];
                let ts_type = rust_type_to_ts(&arg.rust_type);
                collect_custom_types(&arg.rust_type, &mut type_imports);
                ts_type
            } else {
                let fields: Vec<String> = func
                    .args
                    .iter()
                    .map(|arg| {
                        let ts_type = rust_type_to_ts(&arg.rust_type);
                        collect_custom_types(&arg.rust_type, &mut type_imports);
                        format!("{}: {}", arg.name, ts_type)
                    })
                    .collect();
                format!("{{ {} }}", fields.join(", "))
            };

            let result_type = rust_type_to_ts(&func.return_type);
            collect_custom_types(&func.return_type, &mut type_imports);

            let ts_name = to_camel_case(&func.name);

            match func.kind {
                FunctionKind::Query => {
                    queries.push(format!(
                        "export const {} = createQuery<{}, {}>(\"{}\");",
                        ts_name, args_type, result_type, func.name
                    ));
                }
                FunctionKind::Mutation => {
                    mutations.push(format!(
                        "export const {} = createMutation<{}, {}>(\"{}\");",
                        ts_name, args_type, result_type, func.name
                    ));
                }
                FunctionKind::Action => {
                    bindings.push(format!(
                        "export const {} = createAction<{}, {}>(\"{}\");",
                        ts_name, args_type, result_type, func.name
                    ));
                }
                FunctionKind::Job => {
                    let factory_name = format!("create{}Job", to_pascal_case(&func.name));
                    jobs.push(format!(
                        "export const {} = () => createJobTracker<{}>(\"{}\");",
                        factory_name, args_type, func.name
                    ));
                }
                FunctionKind::Workflow => {
                    let factory_name = format!("create{}Workflow", to_pascal_case(&func.name));
                    workflows.push(format!(
                        "export const {} = () => createWorkflowTracker<{}>(\"{}\");",
                        factory_name, args_type, func.name
                    ));
                }
                FunctionKind::Cron => {}
            }
        }

        output.push_str("// Auto-generated by FORGE - DO NOT EDIT\n\n");

        // Determine which helpers are needed based on function types
        let has_actions = !bindings.is_empty();
        let has_jobs = !jobs.is_empty();
        let has_workflows = !workflows.is_empty();
        let mut helpers: Vec<&str> = vec!["createQuery", "createMutation"];
        if has_actions {
            helpers.push("createAction");
        }
        if has_jobs {
            helpers.push("createJobTracker");
        }
        if has_workflows {
            helpers.push("createWorkflowTracker");
        }
        output.push_str(&format!(
            "import {{ {} }} from \"@forge/svelte\";\n",
            helpers.join(", ")
        ));

        if !type_imports.is_empty() {
            type_imports.sort();
            type_imports.dedup();
            output.push_str("import type {\n");
            for t in &type_imports {
                output.push_str(&format!("  {},\n", t));
            }
            output.push_str("} from \"./types\";\n");
        }

        queries.sort();
        mutations.sort();
        jobs.sort();
        workflows.sort();

        if !queries.is_empty() {
            output.push_str("\n// Queries\n");
            for q in &queries {
                output.push_str(q);
                output.push('\n');
            }
        }

        if !mutations.is_empty() {
            output.push_str("\n// Mutations\n");
            for m in &mutations {
                output.push_str(m);
                output.push('\n');
            }
        }

        for b in &bindings {
            output.push_str(b);
            output.push('\n');
        }

        if !jobs.is_empty() {
            output.push_str("\n// Jobs\n");
            for j in &jobs {
                output.push_str(j);
                output.push('\n');
            }
        }

        if !workflows.is_empty() {
            output.push_str("\n// Workflows\n");
            for w in &workflows {
                output.push_str(w);
                output.push('\n');
            }
        }

        Ok(output)
    }
}

fn collect_custom_types(rust_type: &RustType, imports: &mut Vec<String>) {
    match rust_type {
        RustType::Custom(name) => {
            if name != "()" && !name.starts_with("Vec<") && !name.starts_with("HashMap<") {
                imports.push(name.clone());
            }
        }
        RustType::Option(inner) | RustType::Vec(inner) => collect_custom_types(inner, imports),
        _ => {}
    }
}

fn rust_type_to_ts(rust_type: &RustType) -> String {
    match rust_type {
        RustType::String | RustType::Uuid | RustType::DateTime | RustType::Date => {
            "string".to_string()
        }
        RustType::I32 | RustType::I64 | RustType::F32 | RustType::F64 => "number".to_string(),
        RustType::Bool => "boolean".to_string(),
        RustType::Json => "unknown".to_string(),
        RustType::Bytes => "Uint8Array".to_string(),
        RustType::Option(inner) => format!("{} | null", rust_type_to_ts(inner)),
        RustType::Vec(inner) => format!("{}[]", rust_type_to_ts(inner)),
        RustType::Custom(name) => {
            if name == "()" {
                return "void".to_string();
            }
            if let Some(inner) = name.strip_prefix("Vec<").and_then(|s| s.strip_suffix('>')) {
                return format!("{}[]", inner);
            }
            if name.starts_with("HashMap<") || name.starts_with("std::collections::HashMap<") {
                let inner = name
                    .strip_prefix("HashMap<")
                    .or_else(|| name.strip_prefix("std::collections::HashMap<"))
                    .and_then(|s| s.strip_suffix('>'))
                    .unwrap_or("string, unknown");
                let parts: Vec<&str> = inner.splitn(2, ',').map(|s| s.trim()).collect();
                if parts.len() == 2 {
                    let key_type = "string";
                    let value_type = match parts[1] {
                        "String" | "&str" | "str" => "string",
                        "i32" | "i64" | "u32" | "u64" | "f32" | "f64" => "number",
                        "bool" => "boolean",
                        other => other,
                    };
                    return format!("Record<{}, {}>", key_type, value_type);
                }
                return "Record<string, unknown>".to_string();
            }
            name.clone()
        }
    }
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;

    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_uppercase().next().unwrap_or(c));
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_uppercase().next().unwrap_or(c));
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use forge_core::schema::{FunctionArg, FunctionDef};

    #[test]
    fn test_api_generator_creation() {
        let generator = ApiGenerator::new("/tmp/forge");
        assert_eq!(generator.output_dir, PathBuf::from("/tmp/forge"));
    }

    #[test]
    fn test_generate_empty_registry() {
        let generator = ApiGenerator::new("/tmp/forge");
        let registry = SchemaRegistry::new();
        let content = generator.generate(&registry).unwrap();
        assert!(content.contains("Auto-generated by FORGE"));
        assert!(content.contains("import { createQuery, createMutation }"));
    }

    #[test]
    fn test_generate_with_functions() {
        let generator = ApiGenerator::new("/tmp/forge");
        let registry = SchemaRegistry::new();

        // Add a query function
        let mut func = FunctionDef::query("get_user", RustType::Custom("User".to_string()));
        func.args.push(FunctionArg::new("id", RustType::Uuid));
        registry.register_function(func);

        // Add a mutation function
        let mut func = FunctionDef::mutation("create_user", RustType::Custom("User".to_string()));
        func.args.push(FunctionArg::new("name", RustType::String));
        func.args.push(FunctionArg::new("email", RustType::String));
        registry.register_function(func);

        let content = generator.generate(&registry).unwrap();

        // Check that bindings are generated
        assert!(content.contains("export const getUser = createQuery"));
        assert!(content.contains("export const createUser = createMutation"));
    }

    #[test]
    fn test_rust_type_to_ts() {
        assert_eq!(rust_type_to_ts(&RustType::String), "string");
        assert_eq!(rust_type_to_ts(&RustType::I32), "number");
        assert_eq!(rust_type_to_ts(&RustType::Bool), "boolean");
        assert_eq!(rust_type_to_ts(&RustType::Uuid), "string");
        assert_eq!(
            rust_type_to_ts(&RustType::Option(Box::new(RustType::String))),
            "string | null"
        );
        assert_eq!(
            rust_type_to_ts(&RustType::Vec(Box::new(RustType::I32))),
            "number[]"
        );
        assert_eq!(rust_type_to_ts(&RustType::Custom("()".to_string())), "void");
    }

    #[test]
    fn test_to_camel_case() {
        assert_eq!(to_camel_case("get_user"), "getUser");
        assert_eq!(to_camel_case("create_project_task"), "createProjectTask");
        assert_eq!(to_camel_case("getUser"), "getUser");
    }

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("export_users"), "ExportUsers");
        assert_eq!(
            to_pascal_case("account_verification"),
            "AccountVerification"
        );
        assert_eq!(to_pascal_case("ExportUsers"), "ExportUsers");
    }
}
