use forge_core::schema::{FunctionKind, RustType, SchemaRegistry};

use super::Error;

/// Generates TypeScript API bindings.
#[derive(Default)]
pub struct ApiGenerator;

impl ApiGenerator {
    /// Create a new API generator.
    pub fn new() -> Self {
        Self
    }

    pub fn generate(&self, registry: &SchemaRegistry) -> Result<String, Error> {
        let mut output = String::new();
        let mut type_imports = Vec::new();
        let functions = registry.all_functions();
        let mut queries = Vec::new();
        let mut subscriptions = Vec::new();
        let mut mutations = Vec::new();
        let mut jobs = Vec::new();
        let mut workflows = Vec::new();

        for func in &functions {
            let has_args = !func.args.is_empty();
            let args_type = if func.args.is_empty() {
                "null".to_string()
            } else if func.args.len() == 1 {
                let arg = &func.args[0];
                let ts_type = rust_type_to_ts(&arg.rust_type);
                collect_custom_types(&arg.rust_type, &mut type_imports);
                // Custom Args/Input types from Rust macros are used directly
                let is_custom_args_type = matches!(&arg.rust_type, RustType::Custom(name)
                    if name.ends_with("Args") || name.contains("Args")
                    || name.ends_with("Input") || name.contains("Input"));
                if is_custom_args_type {
                    ts_type
                } else {
                    format!("{{ {}: {} }}", arg.name, ts_type)
                }
            } else {
                let fields: Vec<String> = func
                    .args
                    .iter()
                    .map(|arg| {
                        let ts_type = rust_type_to_ts(&arg.rust_type);
                        collect_custom_types(&arg.rust_type, &mut type_imports);
                        format!("{}: {}", arg.name, ts_type)
                    })
                    .collect();
                format!("{{ {} }}", fields.join(", "))
            };

            let ts_name = to_camel_case(&func.name);

            // Check if any argument contains an Upload type
            let has_upload = func.args.iter().any(|arg| contains_upload(&arg.rust_type));

            match func.kind {
                FunctionKind::Query => {
                    let result_type = rust_type_to_ts_return(&func.return_type);
                    collect_custom_types(&func.return_type, &mut type_imports);
                    queries.push(gen_rpc_binding(
                        &ts_name,
                        has_args,
                        &args_type,
                        &result_type,
                        &func.name,
                        false, // queries don't use file uploads
                    ));
                    subscriptions.push(gen_subscription_binding(
                        &ts_name,
                        has_args,
                        &args_type,
                        &result_type,
                        &func.name,
                    ));
                }
                FunctionKind::Mutation => {
                    let result_type = rust_type_to_ts_return(&func.return_type);
                    collect_custom_types(&func.return_type, &mut type_imports);
                    mutations.push(gen_rpc_binding(
                        &ts_name,
                        has_args,
                        &args_type,
                        &result_type,
                        &func.name,
                        has_upload,
                    ));
                }
                FunctionKind::Job => {
                    let factory_name = format!("track{}", to_pascal_case(&func.name));
                    let output_type = rust_type_to_ts_return(&func.return_type);
                    collect_custom_types(&func.return_type, &mut type_imports);
                    jobs.push(gen_store_binding(
                        &factory_name,
                        has_args,
                        &args_type,
                        &output_type,
                        &func.name,
                        "createJobStore",
                    ));
                }
                FunctionKind::Workflow => {
                    let factory_name = format!("track{}", to_pascal_case(&func.name));
                    let output_type = rust_type_to_ts_return(&func.return_type);
                    collect_custom_types(&func.return_type, &mut type_imports);
                    workflows.push(gen_store_binding(
                        &factory_name,
                        has_args,
                        &args_type,
                        &output_type,
                        &func.name,
                        "createWorkflowStore",
                    ));
                }
                FunctionKind::Cron => {}
            }
        }

        output.push_str("// Auto-generated by FORGE - DO NOT EDIT\n\n");

        let has_subscriptions = !subscriptions.is_empty();
        let has_jobs = !jobs.is_empty();
        let has_workflows = !workflows.is_empty();
        let mut helpers: Vec<&str> = vec!["getForgeClient"];
        if has_subscriptions {
            helpers.push("createSubscriptionStore");
        }
        if has_jobs {
            helpers.push("createJobStore");
        }
        if has_workflows {
            helpers.push("createWorkflowStore");
        }
        output.push_str(&format!(
            "import {{ {} }} from \"@forge/svelte\";\n",
            helpers.join(", ")
        ));

        if !type_imports.is_empty() {
            type_imports.sort();
            type_imports.dedup();
            output.push_str("import type {\n");
            for t in &type_imports {
                output.push_str(&format!("  {},\n", t));
            }
            output.push_str("} from \"./types\";\n");
        }

        queries.sort();
        subscriptions.sort();
        mutations.sort();
        jobs.sort();
        workflows.sort();

        if !queries.is_empty() {
            output.push_str("\n// Queries\n");
            for q in &queries {
                output.push_str(q);
                output.push('\n');
            }
        }

        if !subscriptions.is_empty() {
            output.push_str("\n// Subscriptions\n");
            for s in &subscriptions {
                output.push_str(s);
                output.push('\n');
            }
        }

        if !mutations.is_empty() {
            output.push_str("\n// Mutations\n");
            for m in &mutations {
                output.push_str(m);
                output.push('\n');
            }
        }

        if !jobs.is_empty() {
            output.push_str("\n// Jobs\n");
            for j in &jobs {
                output.push_str(j);
                output.push('\n');
            }
        }

        if !workflows.is_empty() {
            output.push_str("\n// Workflows\n");
            for w in &workflows {
                output.push_str(w);
                output.push('\n');
            }
        }

        Ok(output)
    }
}

fn gen_rpc_binding(
    ts_name: &str,
    has_args: bool,
    args_type: &str,
    result_type: &str,
    func_name: &str,
    has_upload: bool,
) -> String {
    let method = if has_upload { "callWithFiles" } else { "call" };
    if has_args {
        format!(
            "export const {} = (args: {}): Promise<{}> =>\n  getForgeClient().{}(\"{}\", args);",
            ts_name, args_type, result_type, method, func_name
        )
    } else {
        format!(
            "export const {} = (): Promise<{}> =>\n  getForgeClient().call(\"{}\", null);",
            ts_name, result_type, func_name
        )
    }
}

/// Check if a RustType contains an Upload type (directly or nested).
fn contains_upload(rust_type: &RustType) -> bool {
    match rust_type {
        RustType::Upload => true,
        RustType::Option(inner) | RustType::Vec(inner) => contains_upload(inner),
        RustType::Custom(name) => name == "Upload",
        _ => false,
    }
}

fn gen_store_binding(
    factory_name: &str,
    has_args: bool,
    args_type: &str,
    output_type: &str,
    func_name: &str,
    store_fn: &str,
) -> String {
    if has_args {
        format!(
            "export const {} = (args: {}) =>\n  {}<{}, {}>(\"{}\", args);",
            factory_name, args_type, store_fn, args_type, output_type, func_name
        )
    } else {
        format!(
            "export const {} = () =>\n  {}<null, {}>(\"{}\", null);",
            factory_name, store_fn, output_type, func_name
        )
    }
}

fn gen_subscription_binding(
    ts_name: &str,
    has_args: bool,
    args_type: &str,
    result_type: &str,
    func_name: &str,
) -> String {
    // Use Store$ suffix - the runes-native $ suffix is in reactive.svelte.ts
    if has_args {
        format!(
            "export const {}Store$ = (args: {}) =>\n  createSubscriptionStore<{}, {}>(\"{}\", args);",
            ts_name, args_type, args_type, result_type, func_name
        )
    } else {
        format!(
            "export const {}Store$ = () =>\n  createSubscriptionStore<null, {}>(\"{}\", null);",
            ts_name, result_type, func_name
        )
    }
}

fn collect_custom_types(rust_type: &RustType, imports: &mut Vec<String>) {
    match rust_type {
        RustType::Custom(name) => {
            // Skip unit type, container types, and primitive-mapped types
            let skip = name == "()"
                || name.starts_with("Vec<")
                || name.starts_with("HashMap<")
                || matches!(
                    name.as_str(),
                    "Instant" | "LocalDate" | "LocalTime" | "Upload" | "Bytes"
                );
            if !skip {
                imports.push(name.clone());
            }
        }
        RustType::Option(inner) | RustType::Vec(inner) => collect_custom_types(inner, imports),
        RustType::Instant
        | RustType::LocalDate
        | RustType::LocalTime
        | RustType::Upload
        | RustType::Bytes => {}
        _ => {}
    }
}

fn rust_type_to_ts(rust_type: &RustType) -> String {
    rust_type_to_ts_inner(rust_type, false)
}

fn rust_type_to_ts_return(rust_type: &RustType) -> String {
    rust_type_to_ts_inner(rust_type, true)
}

fn rust_type_to_ts_inner(rust_type: &RustType, is_return: bool) -> String {
    match rust_type {
        RustType::String | RustType::Uuid | RustType::DateTime | RustType::Date => {
            "string".to_string()
        }
        RustType::Instant | RustType::LocalDate | RustType::LocalTime => "string".to_string(),
        RustType::Upload => "File | Blob".to_string(),
        RustType::I32 | RustType::I64 | RustType::F32 | RustType::F64 => "number".to_string(),
        RustType::Bool => "boolean".to_string(),
        RustType::Json => "unknown".to_string(),
        RustType::Bytes => {
            if is_return {
                "Blob".to_string()
            } else {
                "Uint8Array".to_string()
            }
        }
        RustType::Option(inner) => format!("{} | null", rust_type_to_ts_inner(inner, is_return)),
        RustType::Vec(inner) => format!("{}[]", rust_type_to_ts_inner(inner, is_return)),
        RustType::Custom(name) => {
            if name == "()" {
                return "void".to_string();
            }
            if name == "Upload" {
                return "File | Blob".to_string();
            }
            if let Some(inner) = name.strip_prefix("Vec<").and_then(|s| s.strip_suffix('>')) {
                return format!("{}[]", inner);
            }
            if name.starts_with("HashMap<") || name.starts_with("std::collections::HashMap<") {
                let inner = name
                    .strip_prefix("HashMap<")
                    .or_else(|| name.strip_prefix("std::collections::HashMap<"))
                    .and_then(|s| s.strip_suffix('>'))
                    .unwrap_or("string, unknown");
                let parts: Vec<&str> = inner.splitn(2, ',').map(|s| s.trim()).collect();
                if parts.len() == 2 {
                    let key_type = "string";
                    let value_type = match parts[1] {
                        "String" | "&str" | "str" => "string",
                        "i32" | "i64" | "u32" | "u64" | "f32" | "f64" => "number",
                        "bool" => "boolean",
                        other => other,
                    };
                    return format!("Record<{}, {}>", key_type, value_type);
                }
                return "Record<string, unknown>".to_string();
            }
            name.clone()
        }
    }
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;

    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_uppercase().next().unwrap_or(c));
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_uppercase().next().unwrap_or(c));
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use forge_core::schema::{FunctionArg, FunctionDef};

    #[test]
    fn test_generate_empty_registry() {
        let generator = ApiGenerator::new();
        let registry = SchemaRegistry::new();
        let content = generator.generate(&registry).unwrap();
        assert!(content.contains("Auto-generated by FORGE"));
        assert!(content.contains("import { getForgeClient }"));
    }

    #[test]
    fn test_generate_with_functions() {
        let generator = ApiGenerator::new();
        let registry = SchemaRegistry::new();

        let mut func = FunctionDef::query("get_user", RustType::Custom("User".to_string()));
        func.args.push(FunctionArg::new("id", RustType::Uuid));
        registry.register_function(func);

        let mut func = FunctionDef::mutation("create_user", RustType::Custom("User".to_string()));
        func.args.push(FunctionArg::new("name", RustType::String));
        func.args.push(FunctionArg::new("email", RustType::String));
        registry.register_function(func);

        let content = generator.generate(&registry).unwrap();

        assert!(content.contains("export const getUser = (args:"));
        assert!(content.contains("getForgeClient().call(\"get_user\""));
        assert!(content.contains("export const getUserStore$ = (args:"));
        assert!(content.contains("createSubscriptionStore"));
        assert!(content.contains("export const createUser = (args:"));
        assert!(content.contains("getForgeClient().call(\"create_user\""));
    }

    #[test]
    fn test_generate_no_arg_subscription() {
        let generator = ApiGenerator::new();
        let registry = SchemaRegistry::new();

        let func = FunctionDef::query(
            "list_users",
            RustType::Vec(Box::new(RustType::Custom("User".to_string()))),
        );
        registry.register_function(func);

        let content = generator.generate(&registry).unwrap();

        assert!(content.contains("export const listUsersStore$ = () =>"));
        assert!(content.contains("createSubscriptionStore<null, User[]>(\"list_users\", null)"));
    }

    #[test]
    fn test_rust_type_to_ts() {
        assert_eq!(rust_type_to_ts(&RustType::String), "string");
        assert_eq!(rust_type_to_ts(&RustType::I32), "number");
        assert_eq!(rust_type_to_ts(&RustType::Bool), "boolean");
        assert_eq!(rust_type_to_ts(&RustType::Uuid), "string");
        assert_eq!(
            rust_type_to_ts(&RustType::Option(Box::new(RustType::String))),
            "string | null"
        );
        assert_eq!(
            rust_type_to_ts(&RustType::Vec(Box::new(RustType::I32))),
            "number[]"
        );
        assert_eq!(rust_type_to_ts(&RustType::Custom("()".to_string())), "void");
    }

    #[test]
    fn test_new_datetime_types() {
        // New datetime types should map to string
        assert_eq!(rust_type_to_ts(&RustType::Instant), "string");
        assert_eq!(rust_type_to_ts(&RustType::LocalDate), "string");
        assert_eq!(rust_type_to_ts(&RustType::LocalTime), "string");
    }

    #[test]
    fn test_upload_type() {
        // Upload should map to File | Blob for args
        assert_eq!(rust_type_to_ts(&RustType::Upload), "File | Blob");
    }

    #[test]
    fn test_mutation_with_upload_uses_multipart() {
        let generator = ApiGenerator::new();
        let registry = SchemaRegistry::new();

        // Mutation with Upload arg should use callWithFiles
        let mut func = FunctionDef::mutation("upload_avatar", RustType::Custom("User".to_string()));
        func.args.push(FunctionArg::new("user_id", RustType::Uuid));
        func.args.push(FunctionArg::new("file", RustType::Upload));
        registry.register_function(func);

        // Mutation without Upload should use regular call
        let mut func = FunctionDef::mutation("update_name", RustType::Custom("User".to_string()));
        func.args.push(FunctionArg::new("name", RustType::String));
        registry.register_function(func);

        let content = generator.generate(&registry).unwrap();

        // Upload mutation should use callWithFiles
        assert!(content.contains("getForgeClient().callWithFiles(\"upload_avatar\""));
        // Non-upload mutation should use regular call
        assert!(content.contains("getForgeClient().call(\"update_name\""));
    }

    #[test]
    fn test_contains_upload() {
        assert!(contains_upload(&RustType::Upload));
        assert!(contains_upload(&RustType::Option(Box::new(
            RustType::Upload
        ))));
        assert!(contains_upload(&RustType::Vec(Box::new(RustType::Upload))));
        assert!(contains_upload(&RustType::Custom("Upload".to_string())));
        assert!(!contains_upload(&RustType::String));
        assert!(!contains_upload(&RustType::Custom("User".to_string())));
    }

    #[test]
    fn test_bytes_return_type() {
        // Bytes as return type should map to Blob
        assert_eq!(rust_type_to_ts_return(&RustType::Bytes), "Blob");
        // Bytes as arg type should map to Uint8Array
        assert_eq!(rust_type_to_ts(&RustType::Bytes), "Uint8Array");
    }

    #[test]
    fn test_to_camel_case() {
        assert_eq!(to_camel_case("get_user"), "getUser");
        assert_eq!(to_camel_case("create_project_task"), "createProjectTask");
        assert_eq!(to_camel_case("getUser"), "getUser");
    }

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("export_users"), "ExportUsers");
        assert_eq!(
            to_pascal_case("account_verification"),
            "AccountVerification"
        );
        assert_eq!(to_pascal_case("ExportUsers"), "ExportUsers");
    }
}
