//! TypeScript code generation for SvelteKit frontends.
//!
//! The orchestrator generates all TypeScript artifacts from the schema registry.
//! Each sub-module is a pure function `generate(...) -> Result<String>` that
//! produces file content without touching the filesystem.

mod api;
mod client;
mod reactive;
mod stores;
mod types;

use std::path::PathBuf;

use forge_core::schema::{FunctionKind, SchemaRegistry};

use crate::binding::BindingSet;

/// Runes content shared between schema-aware and stub generation paths.
pub const RUNES_SVELTE_TS: &str = r#"// Auto-generated by FORGE - DO NOT EDIT
import type { SubscriptionStore } from "@forge-rs/svelte";
import type { SubscriptionResult } from "@forge-rs/svelte";

export interface ReactiveQuery<T> extends SubscriptionResult<T> {
  unsubscribe: () => void;
}

export function toReactive<T>(store: SubscriptionStore<T>): ReactiveQuery<T> {
  const state: ReactiveQuery<T> = $state({
    loading: true,
    data: null,
    error: null,
    stale: false,
    unsubscribe: () => {
      unsubscribeCallback();
      store.unsubscribe();
    },
  });

  const unsubscribeCallback = store.subscribe((s) => {
    state.loading = s.loading;
    state.data = s.data;
    state.error = s.error;
    state.stale = s.stale;
  });

  return state;
}
"#;

/// Options for TypeScript code generation.
#[derive(Debug, Clone, Default)]
pub struct GenerateOptions {
    /// Generate auth.svelte.ts when auth is configured.
    pub generate_auth_store: bool,
}

pub struct TypeScriptGenerator {
    output_dir: PathBuf,
    options: GenerateOptions,
}

impl TypeScriptGenerator {
    /// Create a new TypeScript generator.
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        Self {
            output_dir: output_dir.into(),
            options: GenerateOptions::default(),
        }
    }

    /// Create a new TypeScript generator with options.
    pub fn with_options(output_dir: impl Into<PathBuf>, options: GenerateOptions) -> Self {
        Self {
            output_dir: output_dir.into(),
            options,
        }
    }

    /// Generate all TypeScript artifacts and write them to disk.
    pub fn generate(&self, registry: &SchemaRegistry) -> Result<(), Error> {
        std::fs::create_dir_all(&self.output_dir)?;

        let bindings = BindingSet::from_registry(registry);

        std::fs::write(self.output_dir.join("types.ts"), types::generate(registry)?)?;
        std::fs::write(self.output_dir.join("api.ts"), api::generate(&bindings)?)?;
        std::fs::write(
            self.output_dir.join("runes.svelte.ts"),
            Self::runes_content(),
        )?;

        let reactive_content = reactive::generate(&bindings)?;
        if !reactive_content.is_empty() {
            std::fs::write(self.output_dir.join("reactive.svelte.ts"), reactive_content)?;
        }

        std::fs::write(self.output_dir.join("stores.ts"), stores::generate()?)?;

        if self.options.generate_auth_store {
            std::fs::write(self.output_dir.join("auth.svelte.ts"), Self::auth_content())?;
        }

        std::fs::write(
            self.output_dir.join("index.ts"),
            self.generate_index(registry),
        )?;

        Ok(())
    }

    fn runes_content() -> &'static str {
        RUNES_SVELTE_TS
    }

    fn auth_content() -> &'static str {
        r#"// Auto-generated by FORGE - DO NOT EDIT
// Auth store for Svelte 5 with localStorage persistence
import { getForgeClient } from "@forge-rs/svelte";

interface User {
  id: string;
  email: string;
  [key: string]: unknown;
}

interface AuthState {
  token: string | null;
  user: User | null;
}

const AUTH_KEY = "forge_auth";

function loadFromStorage(): AuthState {
  if (typeof localStorage === "undefined") {
    return { token: null, user: null };
  }
  const stored = localStorage.getItem(AUTH_KEY);
  if (!stored) {
    return { token: null, user: null };
  }
  try {
    return JSON.parse(stored);
  } catch {
    return { token: null, user: null };
  }
}

function saveToStorage(state: AuthState): void {
  if (typeof localStorage === "undefined") return;
  if (state.token) {
    localStorage.setItem(AUTH_KEY, JSON.stringify(state));
  } else {
    localStorage.removeItem(AUTH_KEY);
  }
}

class AuthStore {
  #state: AuthState = $state(loadFromStorage());

  get token(): string | null {
    return this.#state.token;
  }

  get user(): User | null {
    return this.#state.user;
  }

  get isAuthenticated(): boolean {
    return this.#state.token !== null;
  }

  setAuth(token: string, user: User): void {
    this.#state = { token, user };
    saveToStorage(this.#state);
    getForgeClient()?.reconnect();
  }

  clearAuth(): void {
    this.#state = { token: null, user: null };
    saveToStorage(this.#state);
    getForgeClient()?.reconnect();
  }
}

export const auth = new AuthStore();

export function getToken(): string | null {
  return auth.token;
}
"#
    }

    fn generate_index(&self, registry: &SchemaRegistry) -> String {
        let has_queries = registry
            .all_functions()
            .iter()
            .any(|f| matches!(f.kind, FunctionKind::Query));

        let mut output = String::from("// Auto-generated by FORGE - DO NOT EDIT\n");
        output.push_str("export * from './types';\n");
        output.push_str("export * from './api';\n");
        output.push_str("export * from './stores';\n");
        output.push_str("export * from './runes.svelte';\n");
        if has_queries {
            output.push_str("export * from './reactive.svelte';\n");
        }
        if self.options.generate_auth_store {
            output.push_str("export * from './auth.svelte';\n");
        }
        output.push_str(
            "export { ForgeClient, ForgeClientError, createForgeClient, ForgeProvider } from '@forge-rs/svelte';\n",
        );
        output
    }

    /// Get the output directory.
    pub fn output_dir(&self) -> &PathBuf {
        &self.output_dir
    }
}

/// Code generation error.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),

    #[error("Parse error in {file}: {message}")]
    Parse { file: String, message: String },

    #[error("Generation error: {0}")]
    Generation(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generator_creation() {
        let generator = TypeScriptGenerator::new("/tmp/forge");
        assert_eq!(generator.output_dir(), &PathBuf::from("/tmp/forge"));
    }

    #[test]
    fn test_generate_index() {
        let generator = TypeScriptGenerator::new("/tmp/forge");
        let registry = SchemaRegistry::new();
        let index = generator.generate_index(&registry);
        assert!(index.contains("'./types'"));
        assert!(index.contains("'./api'"));
        assert!(index.contains("'./stores'"));
        assert!(index.contains("'./runes.svelte'"));
        assert!(index.contains("ForgeClient"));
        assert!(index.contains("createForgeClient"));
        assert!(index.contains("ForgeProvider"));
    }
}
