mod api;
mod client;
mod reactive;
mod stores;
mod types;

pub use api::ApiGenerator;
pub use client::ClientGenerator;
pub use reactive::ReactiveGenerator;
pub use stores::StoreGenerator;
pub use types::TypeGenerator;

use std::path::PathBuf;

use forge_core::schema::{FunctionKind, SchemaRegistry};

pub struct TypeScriptGenerator {
    output_dir: PathBuf,
    type_gen: TypeGenerator,
    api_gen: ApiGenerator,
    reactive_gen: ReactiveGenerator,
    store_gen: StoreGenerator,
}

impl TypeScriptGenerator {
    /// Create a new TypeScript generator.
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        let output_dir = output_dir.into();
        Self {
            output_dir: output_dir.clone(),
            type_gen: TypeGenerator::new(output_dir.clone()),
            api_gen: ApiGenerator::new(),
            reactive_gen: ReactiveGenerator::new(),
            store_gen: StoreGenerator::new(),
        }
    }

    /// Generate all TypeScript artifacts.
    pub fn generate(&self, registry: &SchemaRegistry) -> Result<(), Error> {
        std::fs::create_dir_all(&self.output_dir)?;

        let types_content = self.type_gen.generate(registry)?;
        std::fs::write(self.output_dir.join("types.ts"), types_content)?;

        let api_content = self.api_gen.generate(registry)?;
        std::fs::write(self.output_dir.join("api.ts"), api_content)?;

        // Generate runes.svelte.ts in $lib so Svelte compiles it
        let runes_content = self.generate_runes();
        std::fs::write(self.output_dir.join("runes.svelte.ts"), runes_content)?;

        let reactive_content = self.reactive_gen.generate(registry)?;
        if !reactive_content.is_empty() {
            std::fs::write(self.output_dir.join("reactive.svelte.ts"), reactive_content)?;
        }

        let stores_content = self.store_gen.generate()?;
        std::fs::write(self.output_dir.join("stores.ts"), stores_content)?;

        let index_content = self.generate_index(registry);
        std::fs::write(self.output_dir.join("index.ts"), index_content)?;

        Ok(())
    }

    fn generate_runes(&self) -> String {
        r#"// Auto-generated by FORGE - DO NOT EDIT
import type { SubscriptionStore } from "@forge/svelte";
import type { SubscriptionResult } from "@forge/svelte";

export interface ReactiveQuery<T> extends SubscriptionResult<T> {
  unsubscribe: () => void;
}

export function toReactive<T>(store: SubscriptionStore<T>): ReactiveQuery<T> {
  const state: ReactiveQuery<T> = $state({
    loading: true,
    data: null,
    error: null,
    stale: false,
    unsubscribe: () => {
      unsubscribeCallback();
      store.unsubscribe();
    },
  });

  const unsubscribeCallback = store.subscribe((s) => {
    state.loading = s.loading;
    state.data = s.data;
    state.error = s.error;
    state.stale = s.stale;
  });

  return state;
}
"#
        .to_string()
    }

    fn generate_index(&self, registry: &SchemaRegistry) -> String {
        let has_queries = registry
            .all_functions()
            .iter()
            .any(|f| matches!(f.kind, FunctionKind::Query));

        let mut output = String::from("// Auto-generated by FORGE - DO NOT EDIT\n");
        output.push_str("export * from './types';\n");
        output.push_str("export * from './api';\n");
        output.push_str("export * from './stores';\n");
        output.push_str("export * from './runes.svelte';\n");
        if has_queries {
            output.push_str("export * from './reactive.svelte';\n");
        }
        output.push_str(
            "export { ForgeClient, ForgeClientError, createForgeClient, ForgeProvider } from '@forge/svelte';\n",
        );
        output
    }

    /// Get the output directory.
    pub fn output_dir(&self) -> &PathBuf {
        &self.output_dir
    }
}

/// Code generation error.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),

    #[error("Serialization error: {0}")]
    Serialization(String),

    #[error("Template error: {0}")]
    Template(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generator_creation() {
        let generator = TypeScriptGenerator::new("/tmp/forge");
        assert_eq!(generator.output_dir(), &PathBuf::from("/tmp/forge"));
    }

    #[test]
    fn test_generate_index() {
        let generator = TypeScriptGenerator::new("/tmp/forge");
        let registry = SchemaRegistry::new();
        let index = generator.generate_index(&registry);
        assert!(index.contains("'./types'"));
        assert!(index.contains("'./api'"));
        assert!(index.contains("'./stores'"));
        assert!(index.contains("'./runes.svelte'"));
        assert!(index.contains("ForgeClient"));
        assert!(index.contains("createForgeClient"));
        assert!(index.contains("ForgeProvider"));
    }
}
