use forge_core::schema::{FunctionKind, RustType, SchemaRegistry};

use super::Error;

/// Generates Svelte 5 runes-native reactive bindings.
#[derive(Default)]
pub struct ReactiveGenerator;

impl ReactiveGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate reactive.svelte.ts with runes-native subscription functions.
    pub fn generate(&self, registry: &SchemaRegistry) -> Result<String, Error> {
        let mut output = String::new();
        let functions = registry.all_functions();
        let mut reactive_subscriptions: Vec<(String, String, bool, String)> = Vec::new(); // (ts_name, result_type, has_args, args_type)
        let mut type_imports = Vec::new();

        for func in &functions {
            if !matches!(func.kind, FunctionKind::Query) {
                continue;
            }

            let ts_name = to_camel_case(&func.name);
            let result_type = rust_type_to_ts_return(&func.return_type);
            collect_custom_types(&func.return_type, &mut type_imports);

            let has_args = !func.args.is_empty();
            let args_type = if func.args.is_empty() {
                "null".to_string()
            } else if func.args.len() == 1 {
                let arg = &func.args[0];
                let ts_type = rust_type_to_ts(&arg.rust_type);
                collect_custom_types(&arg.rust_type, &mut type_imports);
                let is_custom_args_type = matches!(&arg.rust_type, RustType::Custom(name)
                    if name.ends_with("Args") || name.contains("Args")
                    || name.ends_with("Input") || name.contains("Input"));
                if is_custom_args_type {
                    ts_type
                } else {
                    format!("{{ {}: {} }}", arg.name, ts_type)
                }
            } else {
                let fields: Vec<String> = func
                    .args
                    .iter()
                    .map(|arg| {
                        let ts_type = rust_type_to_ts(&arg.rust_type);
                        collect_custom_types(&arg.rust_type, &mut type_imports);
                        format!("{}: {}", arg.name, ts_type)
                    })
                    .collect();
                format!("{{ {} }}", fields.join(", "))
            };

            reactive_subscriptions.push((ts_name, result_type, has_args, args_type));
        }

        if reactive_subscriptions.is_empty() {
            return Ok(String::new());
        }

        output.push_str("// Auto-generated by FORGE - DO NOT EDIT\n\n");

        let store_imports: Vec<String> = reactive_subscriptions
            .iter()
            .map(|(name, _, _, _)| format!("{}Store$", name))
            .collect();
        output.push_str(&format!(
            "import {{ {} }} from \"./api\";\n",
            store_imports.join(", ")
        ));
        output.push_str("import { toReactive, type ReactiveQuery } from \"./runes.svelte\";\n");

        if !type_imports.is_empty() {
            type_imports.sort();
            type_imports.dedup();
            output.push_str("import type { ");
            output.push_str(&type_imports.join(", "));
            output.push_str(" } from \"./types\";\n");
        }

        for (ts_name, result_type, has_args, args_type) in &reactive_subscriptions {
            if *has_args {
                output.push_str(&format!(
                    "export const {}$ = (args: {}): ReactiveQuery<{}> =>\n  toReactive({}Store$(args));\n",
                    ts_name, args_type, result_type, ts_name
                ));
            } else {
                output.push_str(&format!(
                    "export const {}$ = (): ReactiveQuery<{}> =>\n  toReactive({}Store$());\n",
                    ts_name, result_type, ts_name
                ));
            }
        }

        Ok(output)
    }
}

fn collect_custom_types(rust_type: &RustType, imports: &mut Vec<String>) {
    match rust_type {
        RustType::Custom(name) => {
            let skip = name == "()"
                || name.starts_with("Vec<")
                || name.starts_with("HashMap<")
                || matches!(
                    name.as_str(),
                    "Instant" | "LocalDate" | "LocalTime" | "Upload" | "Bytes"
                );
            if !skip {
                imports.push(name.clone());
            }
        }
        RustType::Option(inner) | RustType::Vec(inner) => collect_custom_types(inner, imports),
        _ => {}
    }
}

fn rust_type_to_ts(rust_type: &RustType) -> String {
    rust_type_to_ts_inner(rust_type, false)
}

fn rust_type_to_ts_return(rust_type: &RustType) -> String {
    rust_type_to_ts_inner(rust_type, true)
}

fn rust_type_to_ts_inner(rust_type: &RustType, is_return: bool) -> String {
    match rust_type {
        RustType::String | RustType::Uuid | RustType::DateTime | RustType::Date => {
            "string".to_string()
        }
        RustType::Instant | RustType::LocalDate | RustType::LocalTime => "string".to_string(),
        RustType::Upload => "File | Blob".to_string(),
        RustType::I32 | RustType::I64 | RustType::F32 | RustType::F64 => "number".to_string(),
        RustType::Bool => "boolean".to_string(),
        RustType::Json => "unknown".to_string(),
        RustType::Bytes => {
            if is_return {
                "Blob".to_string()
            } else {
                "Uint8Array".to_string()
            }
        }
        RustType::Option(inner) => format!("{} | null", rust_type_to_ts_inner(inner, is_return)),
        RustType::Vec(inner) => format!("{}[]", rust_type_to_ts_inner(inner, is_return)),
        RustType::Custom(name) => {
            if name == "()" {
                return "void".to_string();
            }
            if let Some(inner) = name.strip_prefix("Vec<").and_then(|s| s.strip_suffix('>')) {
                return format!("{}[]", inner);
            }
            name.clone()
        }
    }
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;

    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_uppercase().next().unwrap_or(c));
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use forge_core::schema::FunctionDef;

    #[test]
    fn test_generate_reactive_empty() {
        let generator = ReactiveGenerator::new();
        let registry = SchemaRegistry::new();
        let content = generator.generate(&registry).unwrap();
        assert!(content.is_empty());
    }

    #[test]
    fn test_generate_reactive_with_query() {
        let generator = ReactiveGenerator::new();
        let registry = SchemaRegistry::new();

        let func = FunctionDef::query(
            "list_users",
            RustType::Vec(Box::new(RustType::Custom("User".to_string()))),
        );
        registry.register_function(func);

        let content = generator.generate(&registry).unwrap();
        assert!(content.contains("listUsers$"));
        assert!(content.contains("ReactiveQuery<User[]>"));
        assert!(content.contains("toReactive(listUsersStore$())"));
    }
}
