use super::Error;

#[derive(Default)]
pub struct StoreGenerator;

impl StoreGenerator {
    pub fn new() -> Self {
        Self
    }

    pub fn generate(&self) -> Result<String, Error> {
        Ok(r#"// Auto-generated by FORGE - DO NOT EDIT
export {
  getForgeClient,
  createConnectionStore,
  createQueryStore,
  createSubscriptionStore,
  createJobStore,
  createWorkflowStore,
  dt,
} from '@forge/svelte';
export type {
  Readable,
  ConnectionStatusStore,
  QueryStore,
  SubscriptionStore,
  JobStore,
  WorkflowStore,
} from '@forge/svelte';
"#
        .to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_stores_content() {
        let generator = StoreGenerator::new();
        let content = generator.generate().unwrap();
        assert!(content.contains("@forge/svelte"));
        assert!(content.contains("getForgeClient"));
        assert!(content.contains("createQueryStore"));
        assert!(content.contains("createJobStore"));
        assert!(content.contains("createWorkflowStore"));
        assert!(content.contains("dt"));
    }
}
