use std::path::PathBuf;

use super::Error;

pub struct StoreGenerator {
    #[allow(dead_code)]
    output_dir: PathBuf,
}

impl StoreGenerator {
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        Self {
            output_dir: output_dir.into(),
        }
    }

    pub fn generate(&self) -> Result<String, Error> {
        Ok(r#"// Auto-generated by FORGE - DO NOT EDIT
export { query, subscribe, mutate } from '@forge/svelte';
export type { SubscriptionStore } from '@forge/svelte';
"#
        .to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_store_generator_creation() {
        let generator = StoreGenerator::new("/tmp/forge");
        assert_eq!(generator.output_dir, PathBuf::from("/tmp/forge"));
    }

    #[test]
    fn test_generate_stores_content() {
        let generator = StoreGenerator::new("/tmp/forge");
        let content = generator.generate().unwrap();
        assert!(content.contains("@forge/svelte"));
        assert!(content.contains("query"));
        assert!(content.contains("subscribe"));
        assert!(content.contains("mutate"));
    }
}
