use std::path::PathBuf;

use forge_core::schema::SchemaRegistry;

use super::Error;

pub struct TypeGenerator {
    #[allow(dead_code)]
    output_dir: PathBuf,
}

impl TypeGenerator {
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        Self {
            output_dir: output_dir.into(),
        }
    }

    pub fn generate(&self, registry: &SchemaRegistry) -> Result<String, Error> {
        let mut output = String::new();
        output.push_str("// Auto-generated by FORGE - DO NOT EDIT\n\n");

        let mut tables: Vec<_> = registry.all_tables();
        tables.sort_by(|a, b| a.struct_name.cmp(&b.struct_name));

        for table in tables {
            output.push_str(&format!("export interface {} {{\n", table.struct_name));
            for field in &table.fields {
                output.push_str(&field.to_typescript());
                output.push('\n');
            }
            output.push_str("}\n\n");
        }

        let mut enums: Vec<_> = registry.all_enums();
        enums.sort_by(|a, b| a.name.cmp(&b.name));

        for enum_def in enums {
            output.push_str(&enum_def.to_typescript());
            output.push_str("\n\n");
        }

        output.push_str(
            "export type { ForgeError, QueryResult, SubscriptionResult } from \"@forge/svelte\";\n",
        );

        Ok(output)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use forge_core::schema::{EnumDef, EnumVariant, FieldDef, RustType, TableDef};

    #[test]
    fn test_generator_creation() {
        let generator = TypeGenerator::new("/tmp");
        assert_eq!(generator.output_dir, PathBuf::from("/tmp"));
    }

    #[test]
    fn test_generate_with_table() {
        let generator = TypeGenerator::new("/tmp");
        let registry = SchemaRegistry::new();

        let mut table = TableDef::new("users", "User");
        table.fields.push(FieldDef::new("id", RustType::Uuid));
        table.fields.push(FieldDef::new("email", RustType::String));
        table.fields.push(FieldDef::new(
            "avatar_url",
            RustType::Option(Box::new(RustType::String)),
        ));
        registry.register_table(table);

        let output = generator.generate(&registry).unwrap();
        assert!(output.contains("export interface User {"));
        assert!(output.contains("id: string;"));
        assert!(output.contains("email: string;"));
        assert!(output.contains("avatar_url?: string;"));
    }

    #[test]
    fn test_generate_with_enum() {
        let generator = TypeGenerator::new("/tmp");
        let registry = SchemaRegistry::new();

        let mut enum_def = EnumDef::new("ProjectStatus");
        enum_def.variants.push(EnumVariant::new("Draft"));
        enum_def.variants.push(EnumVariant::new("Active"));
        registry.register_enum(enum_def);

        let output = generator.generate(&registry).unwrap();
        assert!(output.contains("export type ProjectStatus"));
        assert!(output.contains("'draft'"));
        assert!(output.contains("'active'"));
    }

    #[test]
    fn test_generate_reexports_forge_types() {
        let generator = TypeGenerator::new("/tmp");
        let registry = SchemaRegistry::new();
        let output = generator.generate(&registry).unwrap();
        assert!(output.contains("ForgeError"));
        assert!(output.contains("@forge/svelte"));
    }
}
