// Auto-generated by FORGE - DO NOT EDIT
// Auth store for Svelte 5 with localStorage persistence
import { getForgeClient } from "@forge/svelte";

interface User {
  id: string;
  email: string;
  [key: string]: unknown;
}

interface AuthState {
  token: string | null;
  user: User | null;
}

const AUTH_KEY = "forge_auth";

function loadFromStorage(): AuthState {
  if (typeof localStorage === "undefined") {
    return { token: null, user: null };
  }
  const stored = localStorage.getItem(AUTH_KEY);
  if (!stored) {
    return { token: null, user: null };
  }
  try {
    return JSON.parse(stored);
  } catch {
    return { token: null, user: null };
  }
}

function saveToStorage(state: AuthState): void {
  if (typeof localStorage === "undefined") return;
  if (state.token) {
    localStorage.setItem(AUTH_KEY, JSON.stringify(state));
  } else {
    localStorage.removeItem(AUTH_KEY);
  }
}

class AuthStore {
  #state: AuthState = $state(loadFromStorage());

  get token(): string | null {
    return this.#state.token;
  }

  get user(): User | null {
    return this.#state.user;
  }

  get isAuthenticated(): boolean {
    return this.#state.token !== null;
  }

  setAuth(token: string, user: User): void {
    this.#state = { token, user };
    saveToStorage(this.#state);
    getForgeClient()?.reconnect();
  }

  clearAuth(): void {
    this.#state = { token: null, user: null };
    saveToStorage(this.#state);
    getForgeClient()?.reconnect();
  }
}

export const auth = new AuthStore();

export function getToken(): string | null {
  return auth.token;
}
