[application]
name = "demo-frontend"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "demo"

[web.wasm_opt]
level = "s"

[bundle]
identifier = "com.forge.demo"
publisher = "Forge"

[desktop]
enable_default_menu_bar = true
